/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'

const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/enroll': typeof EnrollRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/enroll': typeof EnrollRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/enroll': typeof EnrollRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enroll'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/registrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/enroll'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/registrations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enroll'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/registrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnrollRoute: typeof EnrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EnrollRoute: EnrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
