
CREATE TABLE public.courses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  short_description TEXT NOT NULL,
  description TEXT NOT NULL,
  curriculum TEXT[] NOT NULL DEFAULT '{}',
  features TEXT[] NOT NULL DEFAULT '{}',
  category TEXT NOT NULL CHECK (category IN ('general','kids')),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.courses TO anon, authenticated;
GRANT ALL ON public.courses TO service_role;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Courses are publicly readable" ON public.courses FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.courses (slug, title, short_description, description, curriculum, features, category, sort_order) VALUES
('quran-from-scratch','Qur''an from Scratch','Start your Qur''an journey from the very basics of Arabic letters to fluent recitation.','A beginner-friendly Qur''an program designed for students with no prior background. We start with the Arabic alphabet and progress step-by-step toward confident, correct recitation.', ARRAY['Arabic alphabet & pronunciation','Joining letters and short words','Harakat (vowel marks)','Reading short surahs','Introductory Tajweed rules'], ARRAY['One-on-one or small group classes','Qualified male and female teachers','Flexible scheduling','Progress tracking'], 'general', 1),
('beginner-arabic','Beginner Arabic','Build a strong foundation in Modern Standard Arabic.','For students new to the Arabic language. Focus on reading, writing, vocabulary, and basic grammar to prepare you for Islamic studies and Qur''anic Arabic.', ARRAY['Alphabet & phonics','Reading & writing fundamentals','Core vocabulary','Basic grammar (nouns, verbs, pronouns)','Simple conversation'], ARRAY['Structured weekly lessons','Interactive workbook','Native-level teachers','Homework & feedback'], 'general', 2),
('fiqh-an-nisa','Fiqh An-Nisā','A dedicated jurisprudence course for sisters.','Covering the essential fiqh rulings that every Muslim sister needs to know, taught by qualified female teachers in a safe, sisters-only environment.', ARRAY['Tahārah & purification','Salah rulings','Menstruation & post-natal rulings','Hijab & modesty','Family & marriage fiqh'], ARRAY['Sisters-only classes','Female teachers','Q&A discussions','Practical examples'], 'general', 3),
('idaadi-program','Idaadi Program','A preparatory program for the Aalimiyyah pathway.','A structured preparatory year covering essential Arabic grammar, morphology, and introductory Islamic sciences to prepare you for the Thanawiy program.', ARRAY['Nahw (grammar) basics','Sarf (morphology)','Introductory Fiqh','Aqeedah essentials','Tajweed foundations'], ARRAY['Full curriculum','Multiple weekly classes','Exams & assessments','Certified teachers'], 'general', 4),
('thanawiy-program','Thanawiy Program','The advanced stage of classical Islamic studies.','Continue your journey toward becoming an Aalim/Aalimah with in-depth study of the classical sciences in Arabic.', ARRAY['Advanced Nahw & Sarf','Fiqh of worship & transactions','Usul al-Fiqh','Hadith sciences','Tafsir foundations'], ARRAY['Year-long structured curriculum','Senior scholars','End-of-year examinations','Certificate on completion'], 'general', 5),
('islamic-studies','Islamic Studies','A broad introduction to the core Islamic sciences.','Designed for students who want a well-rounded understanding of Islam — covering aqeedah, fiqh, seerah, and akhlaq in clear, accessible lessons.', ARRAY['Aqeedah (creed)','Essentials of Fiqh','Seerah of the Prophet ﷺ','Akhlaq (Islamic manners)','Selected Hadith'], ARRAY['Beginner friendly','Weekly group classes','Discussion-based learning','Recorded lessons available'], 'general', 6),
('quran-memorization','Qur''an Memorization','A guided Hifz program for adults.','Memorize the Qur''an at your own pace with a dedicated teacher, structured revision plan, and continuous accountability.', ARRAY['Memorization (sabaq)','Recent revision (sabqi)','Older revision (manzil)','Tajweed correction','Goal setting & tracking'], ARRAY['Daily or weekly sessions','One-on-one teacher','Personal Hifz plan','Ijazah pathway available'], 'general', 7),
('tejweed','Tejweed','Master the rules of correct Qur''anic recitation.','For students who can already read the Qur''an and want to perfect their recitation according to the rules of Tajweed.', ARRAY['Makhārij (articulation points)','Sifāt (characteristics)','Rules of Noon & Meem sākin','Madd (elongations)','Practical recitation'], ARRAY['Certified Tajweed teachers','Live correction','Audio practice files','Ijazah-track option'], 'general', 8),
('advanced-arabic','Advanced Arabic','Reach reading fluency in classical Arabic.','For intermediate students moving toward advanced grammar, classical texts, and reading authentic Islamic sources directly in Arabic.', ARRAY['Advanced grammar','Classical text reading','Translation practice','Vocabulary expansion','Composition'], ARRAY['Classical text-based','Small class size','Weekly assignments','Discussion sessions'], 'general', 9),

('kids-arabic-reading','Arabic Reading','Help your child read Arabic with confidence.','A fun, engaging Arabic reading course for kids — from the alphabet to reading short Qur''anic words.', ARRAY['Letters & sounds','Joining letters','Short words & sentences','Reading short surahs'], ARRAY['Kid-friendly teachers','Interactive games','Short focused sessions','Parent progress reports'], 'kids', 1),
('kids-arabic-writing','Arabic Writing','Teach your child to write Arabic letters and words.','A structured writing course for children covering letter shapes, joining, and proper handwriting.', ARRAY['Letter shapes','Letter joining','Word writing','Simple sentences'], ARRAY['Printable worksheets','Live feedback','Patient teachers','Age-appropriate pace'], 'kids', 2),
('kids-quran-memorization','Qur''an Memorization','A gentle Hifz journey for children.','A child-focused memorization program with daily sabaq and regular revision to build strong, lasting memorization.', ARRAY['Daily new memorization','Revision plan','Tajweed correction','Motivation & rewards'], ARRAY['One-on-one classes','Female & male teachers','Hifz tracker for parents','Flexible scheduling'], 'kids', 3),
('kids-adab','Adab — Islamic Morals','Beautiful manners rooted in the Sunnah.','Help your child grow with strong Islamic character — manners with parents, teachers, friends, and toward Allah ﷻ.', ARRAY['Manners with parents','Manners in the masjid','Manners with friends','Honesty & truthfulness','Adab of eating & sleeping'], ARRAY['Story-based lessons','Hadith for kids','Activities & worksheets','Weekly themes'], 'kids', 4),
('kids-hadith','Hadith','Selected hadith for young hearts.','A simple, memorable hadith curriculum that connects children with the words of the Prophet ﷺ.', ARRAY['40 hadith for kids','Word-by-word meaning','Daily application','Memorization'], ARRAY['Memorization tracker','Kid-friendly explanations','Live recitation practice'], 'kids', 5),
('kids-seerah','Seerah — Stories of the Prophets','Inspiring stories from the lives of the Prophets ﷺ.','Bring the seerah to life with engaging storytelling that teaches faith, patience, and good character.', ARRAY['Stories of the Prophets','Life of Prophet Muhammad ﷺ','Lessons & morals','Discussion & reflection'], ARRAY['Storytelling-based','Discussion questions','Age-appropriate content','Weekly themes'], 'kids', 6);
